name: chat_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  cloud_firestore: null
  cupertino_icons: null
  firebase_analytics: null
  firebase_auth: null
  firebase_core: null
  firebase_database: null
  firebase_storage: null
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  google_sign_in: 4.4.3

dev_dependencies:

  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
